#!/bin/sh

RED="\033[0;31m"
GREEN="\033[0;32m"
NC="\033[0m"

if ! head -1 "$1" | grep -qE "^(feat|fix|chore|docs|test|style|refactor|perf|build|ci|revert)(\(.+?\))?: .{1,}$"; then
  echo -e "${RED}[ERROR] Your commit message is invalid.${NC}" >&2
  exit 1
fi

if ! head -1 "$1" | grep -qE "^.{1,88}$"; then
  echo -e "${RED}[ERROR] Your commit message is too long.${NC}" >&2
  exit 1
fi

echo -e "${GREEN}[SUCCESS] Commit message is valid.${NC}"